### ISSUE TITLE
Code is generating scores close to 0 for real and fake videos.

### ISSUE THREAD

**Issue by DKendall99** [BiDAlab/DeepFakesON-Phys#3]

**Comment by MaGyeongBin** [comment]
I'm wondering if this issue has already been addressed—if so, would you mind sharing what the underlying cause was?"

**Comment by MaGyeongBin** [comment]
I'm wondering if this issue has already been addressed—if so, would you mind sharing what the underlying cause was?"

**Comment by femalegeekinsv** [comment]
Any update? I ran into the same issue for both model weight files
